alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: final-final-project-good-team-ye
    match:
      path:
        prefix: /
  - component:
      name: snowyochole-sandwich-gang
    match:
      path:
        prefix: /snowyochole-sandwich-gang
  - component:
      name: snowyochole-sandwich-gang2
    match:
      path:
        prefix: /snowyochole-sandwich-gang2
name: nyc-sandwich-price
region: nyc
services:
- dockerfile_path: mongodb/Dockerfile
  github:
    branch: yml_and_deploy
    deploy_on_push: true
    repo: software-students-spring2025/5-final-final-project-good-team-yes
  http_port: 27017
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: final-final-project-good-team-ye
  source_dir: /
- http_port: 8080
  image:
    registry: snowyochole
    registry_type: DOCKER_HUB
    repository: sandwich-gang
    tag: latest
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: snowyochole-sandwich-gang
- http_port: 8080
  image:
    registry: snowyochole
    registry_type: DOCKER_HUB
    repository: sandwich-gang
    tag: mongo
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: snowyochole-sandwich-gang2
