services:
  web-app:
    build: ./web-app
    container_name: sandwich-tracker-web
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=sandwich_db
      - FLASK_ENV=development
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    build: ./mongodb
    container_name: sandwich-tracker-mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sandwich_db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 