name: MongoDB CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mongodb/**'
      - '.github/workflows/mongodb.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'mongodb/**'
      - '.github/workflows/mongodb.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd mongodb
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t $DOCKER_USERNAME/sandwich-tracker-mongodb:latest .
        docker push $DOCKER_USERNAME/sandwich-tracker-mongodb:latest
        
    - name: Deploy to Digital Ocean
      if: github.event_name != 'pull_request'
      env:
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USER: ${{ secrets.DIGITALOCEAN_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
          cd /opt/sandwich-tracker
          docker-compose pull mongodb
          docker-compose up -d mongodb
        EOF 