name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web-app/requirements.txt
        pip install pytest pytest-cov python-dotenv
    
    - name: Run tests
      env:
        MONGO_URI: "mongodb://nonexistent-host:27017"
        MONGO_DB: "test_sandwich_db"
      run: |
        cd web-app
        python -m pytest test_app.py -v --cov=app 