name: Web App CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd web-app
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        cd web-app
        python -m pytest test_app.py --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./web-app/coverage.xml
        flags: webapptests
        fail_ci_if_error: false
        
    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd web-app
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t $DOCKER_USERNAME/sandwich-tracker-web:latest .
        docker push $DOCKER_USERNAME/sandwich-tracker-web:latest
        
    - name: Deploy to Digital Ocean
      if: github.event_name != 'pull_request'
      env:
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        USER: ${{ secrets.DIGITALOCEAN_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
          cd /opt/sandwich-tracker
          docker-compose pull web-app
          docker-compose up -d web-app
        EOF 